### ISSUE TITLE
ModuleNotFoundError: No module named 'msccl'

### ISSUE THREAD

**Issue by SeekPoint** [Azure/msccl#27]
(base) amd00@MZ32-00:~/yk_repo/NCCL/msccl-tools$ python examples/mscclang/allreduce_a100_allpairs.py --protocol=LL 8 2 > test.xml
Traceback (most recent call last):
  File "/home/amd00/yk_repo/NCCL/msccl-tools/examples/mscclang/allreduce_a100_allpairs.py", line 5, in <module>
    from msccl.language import *
ModuleNotFoundError: No module named 'msccl'
(base) amd00@MZ32-00:~/yk_repo/NCCL/msccl-tools$

**Comment by Andyli1007** [comment]
would you please describe this issue more clearly?

**Comment by Andyli1007** [comment]
since no response in two weeks. will close this issue now.
