### ISSUE TITLE
Question about using acceleraters from brands other than NVIDIA and AMD;

### ISSUE THREAD

**Issue by JASUEXIII** [Azure/msccl#35]
Hi, I'm fresh to this collective communication area. I've read the paper for SCCL and find it interesting and promising to solve my problem. I am considering using SCCL to generate all-reduce strategies for my distributed systems, which require efficient data aggregation. However, I am not clear whether SCCL-tools can produce human-readable descriptions of data movement steps, or if they solely generate code specific to NVIDIA's environments. Could you provide some clarification on this?

**Comment by Andyli1007** [comment]
The SCCL (Scalable Collective Communication Library) generates strategy description files based on XML. These XML files are platform-independent and XML is inherently human-readable. Therefore, SCCL is capable of generating descriptions of data movement steps that are understandable. Currently, SCCL does not provide any other graphical methods for describing strategies.
